### ISSUE TITLE
Add 'Other' Notification Type

### ISSUE THREAD

**Issue by ghost** [fortside/piaware-alerts#1]
Any interest in adding options for other notification types other than to Twitter? Looks like this is one of the only projects that can be easily modified to allow dump10190 JSON feeds to send alerts.

Would be useful to have e-mail or other options (Twilio, Pushover, etc...) for notifying a user about a close-by aircraft.

**Comment by fortside** [comment]
Hey, thanks for checking it out. I don't have any current plans to build it out for more notifications. You're right though, it would be pretty simple to add additional support for other communication options. 
I just add the odd bug-fix or improve error checking whenever it crashes for me. This was a project mostly to satisfy my curiosity, see if I could learn some Python, and re-purpose my Pi. It'd be cool if this was forked or if a pull request was submitted.
